server:
  port: 8081
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://cgzjaqqrbwvikr:9962ea829405943304e55d70f705854edc925164d5141f54143c95e81cbf897a@ec2-3-222-127-167.compute-1.amazonaws.com:5432/dfj77t4o9cjh7h
    username: cgzjaqqrbwvikr
    password: 9962ea829405943304e55d70f705854edc925164d5141f54143c95e81cbf897a
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o Bootcamp DIO - Santander